services:
  
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    restart: unless-stopped
    ports:
      - "4001:80"
    depends_on:
      - php
    networks:
      - back
      - front

  php:
    image: php:8.3-fpm-alpine
    container_name: php
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    networks:
      - back

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "6001:80"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - back
      - front
  
volumes:
  mysql_data:

networks:
  back:
    driver: bridge
  front:
    driver: bridge